 CREATE TABLE TAB007
  (
     IDPRODUTO         INT IDENTITY(1, 1),
     TCODIGOBARRAS     VARCHAR(20) NULL,
     TDESCRICAO        VARCHAR(200) NOT NULL,
     NGRUPO            INT NOT NULL,
     NFABRICANTE       INT NOT NULL,
     NFORNECEDOR       INT NOT NULL,
     LATIVO            BIT NOT NULL,
     LMOVIMENTAESTOQUE INT NOT NULL,
     FESTOQUE          FLOAT NOT NULL,
     NUNIDADE          INT NOT NULL,
     FESTOQUEMIN       FLOAT NULL,
     FESTOQUEMAX       FLOAT NULL,
     DATACADASTRO      DATE NOT NULL,
     NUSUARIO          INT NOT NULL,
	 FPRECO            float NOT NULL,
	 
     CONSTRAINT PKPRODUTOS PRIMARY KEY (IDPRODUTO),
     CONSTRAINT FKGRUPOS_PRODUTOS FOREIGN KEY (NGRUPO) 
	                       REFERENCES TAB006 (IDGRUPO),
     CONSTRAINT FKFABRICANTES_PRODUTOS FOREIGN KEY (NFABRICANTE) 
	                            REFERENCES TAB005 (IDFABRICANTE),
     CONSTRAINT FKFORNECEDORES_PRODUTOS FOREIGN KEY (NFORNECEDOR) 
	                             REFERENCES TAB004 (IDFORNECEDOR),
     CONSTRAINT FKUSUARIO_PRODUTOS FOREIGN KEY (NUSUARIO) 
	                        REFERENCES TAB001 (IDUSUARIO)
  );

EXEC SYS.SP_ADDEXTENDEDPROPERTY
  @NAME=N'MS_DESCRIPTION',
  @VALUE=N'PRODUTOS',
  @LEVEL0TYPE=N'SCHEMA',
  @LEVEL0NAME=N'DBO',
  @LEVEL1TYPE=N'TABLE',
  @LEVEL1NAME=N'TAB007';  