 CREATE TABLE TAB001
  (
     IDUSUARIO     INT IDENTITY(1, 1),
     TNOMECOMPLETO VARCHAR(100) NOT NULL,
     LATIVO        BIT NOT NULL,
     DDATACADASTRO DATE NOT NULL,
     TLOGIN        VARCHAR(50) NOT NULL,
     TSENHA        VARCHAR(100) NOT NULL,
	 
     CONSTRAINT PKUSUARIOS PRIMARY KEY (IDUSUARIO)
  );

EXEC SYS.SP_ADDEXTENDEDPROPERTY
  @NAME=N'MS_DESCRIPTION',
  @VALUE=N'USUARIOS',
  @LEVEL0TYPE=N'SCHEMA',
  @LEVEL0NAME=N'DBO',
  @LEVEL1TYPE=N'TABLE',
  @LEVEL1NAME=N'TAB001';
  
 INSERT INTO TAB001
            (TNOMECOMPLETO,
             LATIVO,
             DDATACADASTRO,
             TLOGIN,
             TSENHA,
             IFOTO)
SELECT 'Administrador',
       1,
       '11/20/2016',
       'admin',
       'admin',
       BULKCOLUMN
FROM   OPENROWSET (BULK 'D:\Documentos\TestAreco\Bin\Graficos\Tab001\admin.bmp',
       SINGLE_BLOB) AS IMAGE;  
    