 CREATE TABLE TAB006
  (
     IDGRUPO    INT IDENTITY(1, 1),
     TDESCRICAO VARCHAR(100) NOT NULL,
	 
     CONSTRAINT PKGRUPOS PRIMARY KEY (IDGRUPO)
  );

EXEC SYS.SP_ADDEXTENDEDPROPERTY
  @NAME=N'MS_DESCRIPTION',
  @VALUE=N'GRUPOS',
  @LEVEL0TYPE=N'SCHEMA',
  @LEVEL0NAME=N'DBO',
  @LEVEL1TYPE=N'TABLE',
  @LEVEL1NAME=N'TAB006';  