 CREATE TABLE TAB003
  (
     IDESTADO INT IDENTITY(1, 1),
     TNOME    VARCHAR(50) NOT NULL,
     TSIGLA   VARCHAR(2) NOT NULL,
     CONSTRAINT PKESTADOS PRIMARY KEY (IDESTADO)
  );

EXEC SYS.SP_ADDEXTENDEDPROPERTY
  @NAME=N'MS_DESCRIPTION',
  @VALUE=N'ESTADOS',
  @LEVEL0TYPE=N'SCHEMA',
  @LEVEL0NAME=N'DBO',
  @LEVEL1TYPE=N'TABLE',
  @LEVEL1NAME=N'TAB003'